name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  initialize:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      is_pr: ${{ steps.check-pr.outputs.is_pr }}
      pr_number: ${{ steps.check-pr.outputs.pr_number }}
      commit_sha: ${{ steps.event-info.outputs.commit_sha }}
    steps:
      - name: Get event info
        id: event-info
        run: |
          echo "commit_sha=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT

      - name: Check if workflow ran on PR
        id: check-pr
        run: |
          PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }}/pulls")
          
          if [ "$(echo $PR_INFO | jq length)" -gt 0 ]; then
            echo "is_pr=true" >> $GITHUB_OUTPUT
            echo "pr_number=$(echo $PR_INFO | jq -r '.[0].number')" >> $GITHUB_OUTPUT
          else
            echo "is_pr=false" >> $GITHUB_OUTPUT
            echo "pr_number=0" >> $GITHUB_OUTPUT
          fi

  download-artifacts:
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          commit: ${{ needs.initialize.outputs.commit_sha }}
          name: build-output
          path: .next
      
      - name: Upload artifact for this workflow
        uses: actions/upload-artifact@v4
        with:
          name: cd-build-output
          path: .next
          retention-days: 1

  preview-deploy:
    name: Deploy Preview
    needs: [initialize, download-artifacts]
    if: ${{ needs.initialize.outputs.is_pr == 'true' }}
    uses: ./.github/workflows/preview.yml
    with:
      artifact-name: cd-build-output
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  comment-pr:
    name: Comment PR
    needs: [initialize, preview-deploy]
    if: ${{ needs.initialize.outputs.is_pr == 'true' }}
    uses: ./.github/workflows/comment-pr.yml
    with:
      preview_url: ${{ needs.preview-deploy.outputs.preview_url }}

  e2e-test:
    name: E2E Tests
    needs: [initialize, preview-deploy]
    if: ${{ needs.initialize.outputs.is_pr == 'true' }}
    uses: ./.github/workflows/e2e-test.yml
    with:
      preview_url: ${{ needs.preview-deploy.outputs.preview_url }}

  production-deploy:
    name: Deploy Production
    needs: [initialize, download-artifacts]
    if: ${{ needs.initialize.outputs.is_pr == 'false' }}
    uses: ./.github/workflows/production.yml
    with:
      artifact-name: cd-build-output
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}