name: CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write # Needs for commenting PRs

jobs:
  build:
    name: Build Application
    uses: ./.github/workflows/build.yml

  deploy-preview:
    name: Deploy Preview
    needs: build
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy-preview.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  comment-pr:
    name: Comment PR
    needs: deploy-preview
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Debug output values
        run: |
          echo "Workflow outputs available:"
          echo "Preview URL from deploy-preview job: ${{ needs.deploy-preview.outputs.preview_url }}"
      
      - name: Comment PR with Preview URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 Deployment previewed successfully!
            Preview: ${{ needs.deploy-preview.outputs.preview_url || 'https://vercel.com/dashboard' }}
          comment_tag: deployment

  deploy-production:
    name: Deploy Production
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-production.yml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}