name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-cache-key.outputs.cache-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate cache key
        id: set-cache-key
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            HASH=$(sha256sum pnpm-lock.yaml | cut -d ' ' -f 1)
          else
            HASH="default-hash"
          fi
          echo "cache-key=${{ runner.os }}-node-modules-${HASH}" >> $GITHUB_OUTPUT

      - name: Debug cache key
        run: echo "Cache key = ${{ steps.set-cache-key.outputs.cache-key }}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ steps.set-cache-key.outputs.cache-key }}

  lint:
    name: Lint Code
    needs: setup
    uses: ./.github/workflows/lint.yml
    with:
      cache-key: ${{ needs.setup.outputs.cache-key }}

  unit-test:
    name: Unit Tests
    needs: setup
    uses: ./.github/workflows/unit-test.yml
    with:
      cache-key: ${{ needs.setup.outputs.cache-key }}

  build:
    name: Build Application
    needs: [setup, lint, unit-test]
    uses: ./.github/workflows/build.yml
    with:
      cache-key: ${{ needs.setup.outputs.cache-key }}

  upload-artifact:
    name: Upload Build Artifact
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .next

      - name: Upload artifact for CD workflow
        uses: actions/upload-artifact@v4
        with:
          name: ci-build-output
          path: .next
          retention-days: 1