name: Comment on PR

on:
  workflow_call:
    inputs:
      preview_url:
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Debug output values
        run: |
          echo "Workflow outputs available:"
          echo "Preview URL from deploy-preview job: ${{ inputs.preview_url }}"

      - name: Comment PR with Preview URL
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 Deployment previewed successfully!
            Preview: ${{ inputs.preview_url }}
          comment_tag: deployment